<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>PMQ.Notifications</PackageId>
    <Version>1.1.1</Version>
    <Product>PMQ.Notifications</Product>
    <Description>
      A package for managing notifications and validations in .NET applications, making it easy to control messages, errors, and business rules in a centralized and strongly-typed way.
    </Description>
    <PackageProjectUrl>https://github.com/PabloMickaelQuevedo/PMQ.Notifications</PackageProjectUrl>
    <RepositoryUrl>https://github.com/PabloMickaelQuevedo/PMQ.Notifications.git</RepositoryUrl>
    <PackageTags>notifications;validation;business-rules;dotnet;domain;ddd</PackageTags>
    <IncludeLicenseFile>true</IncludeLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
